/** Maintenance locale des recettes et profils ; aucun accès compte ni génération. */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { delimiter, dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (path) => readFileSync(resolve(ROOT, path), 'utf8').replace(/^\uFEFF/, '');
const present = (path) => Boolean(path && existsSync(path));
const say = (message) => process.stdout.write(`${message}\n`);
function skillMetadata(path) {
  const header = read(path).match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!header) throw new Error(`En-tête YAML absent : ${path}`);
  const value = (key) => {
    const raw = header[1].match(new RegExp(`^${key}:\\s*(.+)$`, 'm'))?.[1]?.trim();
    if (!raw) throw new Error(`Champ ${key} absent : ${path}`);
    return raw.startsWith('"') ? JSON.parse(raw) : raw.replace(/^'|'$/g, '');
  };
  return { name: value('name'), description: value('description') };
}
function holtSkills() {
  return readdirSync(resolve(ROOT, '.agents/skills'), { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith('holt-'))
    .map((entry) => entry.name)
    .sort();
}
function adapters() {
  const files = new Map();
  const profiles = JSON.parse(read('docs/process/agent-profiles.json'));
  const names = new Set();
  for (const profile of profiles) {
    const claudeName = profile.claudeName ?? profile.name;
    if (!/^holt-[a-z-]+$/.test(profile.name) || names.has(profile.name)) {
      throw new Error(`Nom de profil invalide ou dupliqué : ${profile.name}`);
    }
    if (!/^[a-z-]+$/.test(claudeName) || !/^docs\/process\/agents\/[a-z-]+\.md$/.test(profile.procedure)) {
      throw new Error(`Chemin de profil invalide : ${profile.name}`);
    }
    names.add(profile.name);
    if (!existsSync(resolve(ROOT, profile.procedure)))
      throw new Error(`Procédure absente : ${profile.procedure}`);
    const instruction = `Lire AGENTS.md et docs/INDEX.md comme index, puis ${profile.procedure} et docs/process/AGENT-WORKFLOW.md. Appliquer cette procédure dans le périmètre de la mission. Préserver les autres travaux. Ne pas lancer de sous-agents sans autorisation applicable.`;
    files.set(
      `.codex/agents/${profile.name}.toml`,
      `# Generated by npm run agents:sync; edit docs/process/agent-profiles.json and its procedure.\nname = ${JSON.stringify(profile.name)}\ndescription = ${JSON.stringify(profile.description)}\n${profile.readOnly ? 'sandbox_mode = "read-only"\n' : ''}developer_instructions = ${JSON.stringify(instruction)}\n`,
    );
    files.set(
      `.claude/agents/${claudeName}.md`,
      `---\nname: ${claudeName}\ndescription: ${JSON.stringify(profile.description)}\nmodel: inherit\n${profile.readOnly ? 'tools: Read, Grep, Glob\n' : ''}---\n\n<!-- Generated by npm run agents:sync. -->\n\nLire AGENTS.md, docs/INDEX.md comme index, puis [la procédure](../../${profile.procedure})\net [le contrat de mission](../../docs/process/AGENT-WORKFLOW.md).\nAppliquer la procédure dans le périmètre confié ; préserver les autres travaux.\n`,
    );
  }
  for (const name of holtSkills()) {
    const metadata = skillMetadata(`.agents/skills/${name}/SKILL.md`);
    files.set(
      `.claude/skills/${name}/SKILL.md`,
      `---\nname: ${name}\ndescription: ${JSON.stringify(metadata.description)}\n---\n\n<!-- Generated by npm run agents:sync. -->\n\nLire [le skill canonique](../../../.agents/skills/${name}/SKILL.md) et appliquer sa procédure.\nLes recettes durables et leurs références restent dans docs/.\n`,
    );
  }
  for (const [alias, name] of [
    ['character-creation', 'holt-character'],
    ['mixamo', 'holt-mixamo'],
  ]) {
    files.set(
      `.claude/skills/${alias}/SKILL.md`,
      `---\nname: ${alias}\ndescription: "Legacy invocation for ${name}; use its canonical HOLT workflow."\n---\n\n<!-- Generated by npm run agents:sync; legacy name preserved. -->\n\nLire [le skill canonique](../../../.agents/skills/${name}/SKILL.md) et appliquer sa procédure.\n`,
    );
  }
  return files;
}
function sync(check) {
  const expected = adapters();
  let errors = 0;
  for (const [path, content] of expected) {
    if (check) {
      if (!existsSync(resolve(ROOT, path)) || read(path).replace(/\r\n/g, '\n') !== content) {
        say(`Adaptateur à actualiser : ${path}`);
        errors++;
      }
    } else {
      mkdirSync(dirname(resolve(ROOT, path)), { recursive: true });
      writeFileSync(resolve(ROOT, path), content);
    }
  }
  if (!errors) say(`${expected.size} adaptateurs ${check ? 'à jour' : 'écrits'}.`);
  return errors;
}
function check() {
  let errors = sync(true);
  const paths = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard'], {
    cwd: ROOT,
    encoding: 'utf8',
  })
    .split(/\r?\n/)
    .filter((path) => path.endsWith('.md') && existsSync(resolve(ROOT, path)));
  let links = 0;
  for (const path of paths) {
    const body = read(path);
    if (/^\.agents\/skills\/[^/]+\/SKILL\.md$/.test(path)) {
      const metadata = skillMetadata(path);
      const folder = path.split('/')[2];
      if (metadata.name !== folder || !/^[a-z0-9-]{1,64}$/.test(metadata.name)) {
        say(`Nom de skill incohérent : ${path}`);
        errors++;
      }
    }
    // Ignore fenced examples; paths in actual prose/images remain checked.
    const prose = body.replace(/^```[^\n]*\n[\s\S]*?^```\s*$/gm, '');
    for (const match of prose.matchAll(/\[[^\]]*\]\((?:<([^>]+)>|([^\n)]+))\)/g)) {
      let target = (match[1] ?? match[2]).replace(/\s+["'][^"']*["']$/, '').trim();
      if (/^(?:[a-z][a-z0-9+.-]*:\/\/|mailto:|app:|#)/i.test(target)) continue;
      target = decodeURIComponent(target.split('#')[0].split('?')[0]).replace(/^\/([a-z]:\/)/i, '$1');
      if (!target) continue;
      const absolute = isAbsolute(target) ? target : resolve(ROOT, dirname(path), target);
      const rel = relative(ROOT, absolute).replaceAll('\\', '/');
      // Masters and proofs are deliberately local, absent from fresh checkouts.
      if (rel.startsWith('art-masters/') || rel.startsWith('tmp/') || rel.startsWith('..')) continue;
      links++;
      if (!existsSync(absolute)) {
        say(`Lien absent : ${path} → ${target}`);
        errors++;
      }
    }
  }
  if (!errors) say(`${paths.length} documents et ${links} liens locaux vérifiés.`);
  return errors;
}
function onPath(name) {
  const extensions = process.platform === 'win32' ? ['', '.exe', '.cmd', '.bat'] : [''];
  for (const dir of (process.env.PATH ?? '').split(delimiter)) {
    for (const ext of extensions) {
      const candidate = join(dir, `${name}${ext}`);
      if (existsSync(candidate) && statSync(candidate).isFile()) return candidate;
    }
  }
  return undefined;
}
function doctor() {
  const scope = process.argv.find((arg) => arg.startsWith('--scope='))?.slice(8) ?? 'all';
  if (!['all', 'audio', 'characters', 'core'].includes(scope))
    throw new Error(`Périmètre inconnu : ${scope}`);
  say('Diagnostic local : présence de fichiers, sans exécution des outils ni accès compte.');
  const show = (label, path) =>
    say(
      `${present(path) ? 'Présent' : 'Non visible dans cette session (absent ou accès refusé)'} : ${label}${present(path) ? ` (${path})` : ''}`,
    );
  show('Node', process.execPath);
  show('dépendances du jeu', resolve(ROOT, 'node_modules/typescript/package.json'));
  show(
    'Playwright npm (navigateur à vérifier séparément)',
    resolve(ROOT, 'node_modules/@playwright/test/package.json'),
  );
  let configuredPython;
  if (existsSync(resolve(ROOT, '.mcp.json'))) {
    const config = JSON.parse(read('.mcp.json'));
    configuredPython = config.mcpServers?.mixamo?.command;
  }
  const python = [process.env.HOLT_PYTHON_EXE, onPath('python'), configuredPython].find(present);
  if (scope !== 'core') show('Python', python);
  if (scope === 'all' || scope === 'audio') {
    const cli =
      process.env.HOLT_ELEVENLABS_CLI ??
      (process.platform === 'win32'
        ? resolve(process.env.APPDATA ?? '', 'npm/node_modules/@elevenlabs/cli/bin/cli.js')
        : onPath('elevenlabs'));
    show('CLI ElevenLabs (OAuth à vérifier par auth status)', cli);
    const binaries = resolve(ROOT, 'art-masters/tools/audio-python/imageio_ffmpeg/binaries');
    const bundled = existsSync(binaries)
      ? readdirSync(binaries).find((file) => /^ffmpeg.*\.exe$/.test(file))
      : undefined;
    show(
      'FFmpeg',
      [process.env.FFMPEG_BINARY, onPath('ffmpeg'), bundled ? join(binaries, bundled) : undefined].find(
        present,
      ),
    );
    show('librairies média locales, facultatives', resolve(ROOT, 'art-masters/tools/audio-python'));
  }
  if (scope === 'all' || scope === 'characters') {
    const bash =
      process.platform === 'win32'
        ? [process.env.HOLT_BASH_EXE, 'C:/Program Files/Git/bin/bash.exe', onPath('bash')]
            .filter((path) => path && !/[/\\]system32[/\\]bash\.exe$/i.test(path))
            .find(present)
        : onPath('bash');
    show('Git Bash (Windows) ou Bash (Unix)', bash);
    show(
      'Blender MPFB',
      [
        process.env.BLENDER_EXE,
        'D:/AgenticCoding/tools/blender/app/blender-4.2.23-windows-x64/blender.exe',
      ].find(present),
    );
    show(
      'ressources MPFB',
      [process.env.BLENDER_USER_RESOURCES, 'D:/AgenticCoding/tools/blender/user'].find(present),
    );
    show('serveur Mixamo local (connexion distincte)', 'D:/AgenticCoding/tools/mixamo-mcp/mcp_server.py');
  }
  say('Recettes et limitations : docs/process/TOOLS.md. Les outils média sont facultatifs pour le jeu.');
  const [major, minor] = process.versions.node.split('.').map(Number);
  return major < 20 ||
    (major === 20 && minor < 19) ||
    !existsSync(resolve(ROOT, 'node_modules/typescript/package.json'))
    ? 1
    : 0;
}
const command = process.argv[2];
if (command === 'sync') process.exitCode = sync(process.argv.includes('--check')) ? 1 : 0;
else if (command === 'check') process.exitCode = check() ? 1 : 0;
else if (command === 'doctor') process.exitCode = doctor();
else
  throw new Error(
    'Usage : workflow-tools.mjs check | sync [--check] | doctor [--scope=core|audio|characters|all]',
  );
